backend:
  name: github
  repo: MilanRajkumar/milanrajkumar.github.io

media_folder: static/assets
public_folder: /assets

collections: 
  - name: post
    label: Posts
    folder: src/assets
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Create At, widget: date }
      - { name: body, label: Post, widget: markdown }
      - { name: image, label: Image, widget: image }